### ISSUE TITLE
please increase versionCode with each release

### ISSUE THREAD

**Issue by IzzySoft** [N0-0NE-Dev/NoFasel#1]
The latest release identifies as

    package: name='com.n00nedev.nofasel' versionCode='1' versionName='1.0.7'

So it's still at `versionCode: 1` despite the fact there were already 7 releases before it. As Android uses `versionCode` internally to tell versions apart, this should be increased with each release. Could you please take care for that, starting e.g. with the next release? The proper place most likely [is here](https://github.com/N0-0NE-Dev/NoFasel/blob/main/android/app/build.gradle#L148) (I'm not familiar with React, but that's where gradle has it). Thanks in advance!

**Comment by IzzySoft** [comment]
Thanks, that was fast! Well, I could make a suggestion for your Readme: if you want to, you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to [link here](https://apt.izzysoft.de/fdroid/index/apk/com.n00nedev.nofasel), where your app is present since yesterday. My repo is the largest 3rd-party F-Droid repo and (I've heard) quite popular among the F/LOSS community. The F-Droid client takes care for keeping your app updated on the Androids – and my updater makes sure new releases are fetched from your repo here within 24h of your making them available.

Oh, and I happily provide you the metadata I've set up there, so you can control how your app is presented – by making a PR with the corresponding [Fastlane structures](https://gitlab.com/-/snippets/1895688).

**Comment by N0-0NE-Dev** [comment]
> Thanks, that was fast! Well, I could make a suggestion for your Readme: if you want to, you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to [link here](https://apt.izzysoft.de/fdroid/index/apk/com.n00nedev.nofasel), where your app is present since yesterday. My repo is the largest 3rd-party F-Droid repo and (I've heard) quite popular among the F/LOSS community. The F-Droid client takes care for keeping your app updated on the Androids – and my updater makes sure new releases are fetched from your repo here within 24h of your making them available.
> 
> Oh, and I happily provide you the metadata I've set up there, so you can control how your app is presented – by making a PR with the corresponding [Fastlane structures](https://gitlab.com/-/snippets/1895688).

Yeah your repo is awesome! I thought about putting NoFasel on F-Droid, but ultimately decided that it maybe too complicated for me, but since you have made all the hard work, I am more than happy to add a badge to the readme. Just one question though, does downloads from IzzyOnDroid count towards the GitHub releases downloads?

**Comment by IzzySoft** [comment]
> but ultimately decided that it maybe too complicated for me

Well, it often just sounds so much more complicated than it really is (only in some rare cases it's the opposite) :see_no_evil:

> I am more than happy to add a badge to the readme

Cool, thanks! And let me know if you want to have the metadata here (so you can adjust when something changes with a new update, or even add per-release changelogs to make users eager to update (or rather skip one if it sounds scary), and more).

> does downloads from IzzyOnDroid count towards the GitHub releases downloads?

No. Just one time per release, when my updater fetches the APK. After that it's shipped from my repo. Background is my updater also takes care to check the APK (VirusTotal, library scan and some more), showing the results. So those results should match what the user gets – which I only can guarantee by shipping the APK from my server (as "upstream" could e.g. replace it the other day). Apart from that, the software used (fdroidserver) works that way and wouldn't work with "remote APKs" anyway.

**Comment by N0-0NE-Dev** [comment]
Yeah that sounds great! I will be adding the badge starting from the next release.

> Cool, thanks! And let me know if you want to have the metadata here (so you can adjust when something changes with a new update, or even add per-release changelogs to make users eager to update (or rather skip one if it sounds scary), and more).

Yeah, if you can please tell me where to find the metadata, because I will be changing the screenshots in the repo soon, to reflect the UI changes and I would like to change them in your repo too!

**Comment by IzzySoft** [comment]
> if you can please tell me where to find the metadata

There ^^ :rofl: Enjoy! And if you have questions, just ask. Once the PR has been merged, I'd enable Fastlane for your app in my repo, so changes will be pulled along with new releases.
