### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by HasanAbbadi** [N0-0NE-Dev/NoFasel#12]
**Describe the bug**
When I open the app it gets stuck at the initial loading screen. I even left it for a couple of minutes just to be sure, but to no avail.

**To Reproduce**
1. Download version 1.1.0
2. Open the app
3. Stuck at loading

**Expected behavior**
Get into the main menu.

**Screenshots**
![demo](https://user-images.githubusercontent.com/78548167/217300985-beefe460-426e-4665-9f27-286d7351e672.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8
 - OS: Stock Android Rom
 - Version: 13.0

**Additional context**
no additional information

**Comment by ZooNooU** [comment]
same here, stuck at loading screen.

**Comment by N0-0NE-Dev** [comment]
Hey @HasanAbbadi and @ZooNooU, thanks for bringing this into my attention. I fixed this issue in f34df00c155abcb8f5c80c455ba52b78d9122e11 and pushed an OTA update. Please restart the app a couple of times and it should start working again as normal.

**Comment by OshekharO** [comment]
Still this issue is not solved
