### ISSUE TITLE
Question about Missing Entries

### ISSUE THREAD

**Issue by HasanAbbadi** [N0-0NE-Dev/NoFasel#13]
Hey, I've been testing this app for a bit and looking at the source code, but i noticed something.
Ironically not all movies are actually in [fasel's all-movies category](https://www.faselhd.ws/all-movies).

 For instance you can search for some entries on faselhd and they would show up, but they won't show up in [all-content.json](https://github.com/N0-0NE-Dev/no-fasel-scrapers/blob/main/output/all-content.json).
One example I found is [Luck 2022](https://www.faselhd.ws/?p=154428), but there are some more i've noticed that behave the same way. I don't think it's just me either.

I am not sure if you already knew this or not, thought i should mention it just in case 😃
Best regards.

**Comment by N0-0NE-Dev** [comment]
Hey @HasanAbbadi, thanks for bringing this to my attention. I have already noticed this before and had to add The Batman (2022) manually as it was not listed. Unfortunately, there is really not much I can do about it.

**Comment by HasanAbbadi** [comment]
That's very unfortunate, maybe you could make the search page directly scrape fasel's search?
Unless that conflicts with the current vision you have.

**Comment by N0-0NE-Dev** [comment]
> That's very unfortunate, maybe you could make the search page directly scrape fasel's search? Unless that conflicts with the current vision you have.

Yeah that's a good idea. Maybe I will test it to see if it slows searching too much.

**Comment by HasanAbbadi** [comment]
On another note @N0-0NE-Dev, I just noticed that [foreign movies category](https://www.faselhd.ws/movies) has more than 400 pages while [all-movies](https://www.faselhd.ws/all-movies) has only 150.

The former also includes Batman 2022 and Luck 2022, so you could try using that instead!

**Comment by N0-0NE-Dev** [comment]
Yeah I see. That's interesting, I will switch the scrapers to use movies instead. Thanks you!

**Comment by N0-0NE-Dev** [comment]
Yeah this will probably come in handy, thanks for the data @HasanAbbadi.
