### ISSUE TITLE
Taking forever to open

### ISSUE THREAD

**Issue by OshekharO** [N0-0NE-Dev/NoFasel#15]
**Describe the bug**
I have tried opening the app but it's not loading the homepage. It's been 2 minutes but still not loaded.

**To Reproduce**
1. Open the app
2. See error

**Expected behavior**
Should have loaded the homepage within a second

**Screenshots**
![Screenshot_2023-02-12-19-50-44-40_04aad770f80d7e5bbd6c1fff15b6a3f5](https://user-images.githubusercontent.com/95137948/218316616-3d6d70e8-58ba-4e6b-bda6-68ff2dc41560.jpg)

**Smartphone (please complete the following information):**
 - Device: Realme 7 Pro
 - OS: Android 
 - Version: 12

**Comment by Baker0o7** [comment]
Yes me too

**Comment by N0-0NE-Dev** [comment]
Hey @OshekharO and @Baker0o7, I fixed that issue in edce163 and pushed an OTA update, please restart the app once or twice and it should work normally.

**Comment by Baker0o7** [comment]
Still same issue sir

**Comment by Baker0o7** [comment]
Still same issue I tried with that build too am on android 12 Aosp vanilla build

**Comment by N0-0NE-Dev** [comment]
Can you try to go to [this](https://www.faselhd.ws/) website and tell me if it is blocked in your country?

**Comment by Baker0o7** [comment]
It says checking if the site connection is secure but doesnt open the site

**Comment by N0-0NE-Dev** [comment]
Can you try using a vpn? [This](https://play.google.com/store/apps/details?id=ch.protonvpn.android) one is free and unlimited.

**Comment by Baker0o7** [comment]
Lemme try

**Comment by Baker0o7** [comment]
Tried proton VPN but still same issue sir

**Comment by N0-0NE-Dev** [comment]
What country are you in?

**Comment by OshekharO** [comment]
> Can you try to go to [this](https://www.faselhd.ws/) website and tell me if it is blocked in your country?

It's not blocked in my country ( india ) but still the app is not loading. Tried with vpn also.

**Comment by N0-0NE-Dev** [comment]
> > Can you try to go to [this](https://www.faselhd.ws/) website and tell me if it is blocked in your country?
> 
> It's not blocked in my country ( india ) but still the app is not loading. Tried with vpn also.

Yeah the problem seems to be that fasel is blocking requests that are coming from a webview in certain countries. There is nothing I can do about it unfortunately, but I am working on a scraper for fmovies which should be a better option for you as you would be able to choose the subtitles' language.

**Comment by OshekharO** [comment]
> > > Can you try to go to [this](https://www.faselhd.ws/) website and tell me if it is blocked in your country?
> > 
> > 
> > It's not blocked in my country ( india ) but still the app is not loading. Tried with vpn also.
> 
> Yeah the problem seems to be that fasel is blocking requests that are coming from a webview in certain countries. There is nothing I can do about it unfortunately, but I am working on a scraper for fmovies which should be a better option for you as you would be able to choose the subtitles' language.

Ok, thanks 👍
