### ISSUE TITLE
Material You Support

### ISSUE THREAD

**Issue by ZooNooU** [N0-0NE-Dev/NoFasel#16]
I absolutely love how the app looks now,
but it wouldn't be complete without material you support!
please consider adding this theming option 🙏🏻

**Comment by N0-0NE-Dev** [comment]
Hey @ZooNooU, I am glad that you like the new UI, I will try my best to add material you support in the next release.

**Comment by johnadward2** [comment]
It's not working 😢

**Comment by N0-0NE-Dev** [comment]
> It's not working 😢 loading loading 🌚

Hi I don't think this is the correct issue to have this discussion in, however I suggest you completely delete the app and install the new version, then when prompted to choose a provider choose HDwatched not FaselHD.

**Comment by N0-0NE-Dev** [comment]
> Nope I installed lastest version but it's not working rather version 1.0.4 is working but it also have some problems 🌚

Please open a new issue with more details and perhaps a screenshot of what you are seeing.

**Comment by johnadward2** [comment]
I don't know who to open a new issue but i am sending you screenshot,it is surely a problem from your side,![Screenshot_2023-02-27-19-38-04-52.png](https://user-images.githubusercontent.com/123066031/221592760-a9356967-3e2e-44ef-a4e6-ea2071e57774.png)

 wait

**Comment by N0-0NE-Dev** [comment]
Yeah I can see the problem now, I will fix it as soon as I get the chance, I opened issue number #29 for it, please keep an eye on it.

**Comment by johnadward2** [comment]
Oh finally thank you sir it's amazing app please fix it as soon as possible I am waiting I even used VPN but I didn't work,thank you💜

**Comment by N0-0NE-Dev** [comment]
Hey @ZooNooU, as of version [1.2.0](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.2.0), I have added material you support. Please provide feedback in the discussions tab of what you think.

**Comment by ZooNooU** [comment]
> Hey @ZooNooU, as of version [1.2.0](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.2.0), I have added material you support. Please provide feedback in the discussions tab of what you think.

best way to end my day!
thanks alot man! Ramdan Mubarek to you!
(I honestly thought that you forgot about this 😅)
