### ISSUE TITLE
Could you add this Brazilian sites to watch movies and series:

### ISSUE THREAD

**Issue by Heus-Sueh** [N0-0NE-Dev/NoFasel#18]
vizer.tv
https://m.topflix.vc
https://megaflix.co
https://querofilmeshd.xyz/

thanks in advance

**Comment by Heus-Sueh** [comment]
I also think it's better to enable discussions, so as not to pollute the issues
![Screenshot_20230213_164852](https://user-images.githubusercontent.com/98482469/218560294-92c30d4b-53a3-4a4d-863c-d7dec50ada7d.png)

**Comment by N0-0NE-Dev** [comment]
Hey @Heus-Sueh, I will look into the possibity of scraping the websites you mentioned. Also, I enabled discussions. Thanks for the suggestions!

**Comment by N0-0NE-Dev** [comment]
Hey @Heus-Sueh, as of version [1.1.3](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.3) you can choose hdw as a provider when you first launch the app. All the content from hdw had no subtitles by default you can use an external video player like [vlc ](https://play.google.com/store/apps/details?id=org.videolan.vlc) to add subtitles. I think this is a better option than scraping websites in very language. See #2 #5 and the 1.1.3 release notes for more details.
