### ISSUE TITLE
PLZ ADD HINDI DUBBED MOVIES AND WEBSERIES IN NOFASEL APP 

### ISSUE THREAD

**Issue by rocky1775** [N0-0NE-Dev/NoFasel#2]
PLZ ADD HINDI DUBBED MOVIES AND WEBSERIES IN NOFASEL APP

**Comment by rocky1775** [comment]
Ok Bro Wait

**Comment by rocky1775** [comment]
Movies Download Websites
https://moviesmod.in/
https://moviesflixer.us/

**Comment by rocky1775** [comment]
BRO CAN YOU TELL ME BEST OPEN SOURCE APP TO BLOCK MOBILE CAMERA PLZ

**Comment by N0-0NE-Dev** [comment]
> BRO CAN YOU TELL ME BEST OPEN SOURCE APP TO BLOCK MOBILE CAMERA PLZ

If you use android 12 or higher, there should be a quick settings toggle for camera and microphone access.
![IMG_20230113_045522](https://user-images.githubusercontent.com/109165623/212142716-e225639f-6203-423d-8a49-2643e56fc433.jpg)

**Comment by N0-0NE-Dev** [comment]
Hey @rocky1775, unfortunately all the website that offer hindi dubbed movies are extremly hard to scrape, so I will not be adding any hindi dubbed content, but as of version [1.1.3](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.3) you can choose hdw as a provider when you first launch the app and should work normally, please read the release notes for more information.
