### ISSUE TITLE
NF keep loading

### ISSUE THREAD

**Issue by Sabonk** [N0-0NE-Dev/NoFasel#20]
https://user-images.githubusercontent.com/3258300/218617835-2b88c94d-8c87-43ea-bb2c-e6d336d66c32.mp4

**Comment by N0-0NE-Dev** [comment]
See #17 and #15

**Comment by Heus-Sueh** [comment]
i am having this problem too, i tried to open it with vpn but the problem remains

**Comment by Gadd28** [comment]
Same for me. Everything was working this morning with 1.0.8 version and then decided to upgrade to latest version and loading is Killing me 🥶🥶🥶 rollback to 1.0.8 version but not working anymore and tested with vpn from different countries and Same problem 😵‍💫😵‍💫

**Comment by N0-0NE-Dev** [comment]
> Same for me. Everything was working this morning with 1.0.8 version and then decided to upgrade to latest version and loading is Killing me 🥶🥶🥶 rollback to 1.0.8 version but not working anymore and tested with vpn from different countries and Same problem 😵‍💫😵‍💫

What country are you in?

**Comment by Gadd28** [comment]
France but everything was working great this morning before updating

**Comment by N0-0NE-Dev** [comment]
> France but everything was working great this morning before updating

It's probably because the website was cached.

**Comment by Gadd28** [comment]
I have no issue to access the website 
![Screenshot_2023-02-15-05-09-34-34_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/125402669/218927643-4048c237-7bd5-4c6f-9a91-d3b9135ff571.jpg)

**Comment by N0-0NE-Dev** [comment]
Yeah, it's because the app use a webview to log you into a premium account for this website, but unfortunately they are blocking requests coming from webviews for some countries. Look at #15 and #17.

**Comment by Gadd28** [comment]
Yes thanks already checked cases 15 and 17. Is there any vpn application that is working with nofasel ? I mean which include a country that is not banned ? Thank you

**Comment by N0-0NE-Dev** [comment]
> Yes thanks already checked cases 15 and 17. Is there any vpn application that is working with nofasel ? I mean which include a country that is not banned ? Thank you

If you know a vpn with an Australian server that might work.

**Comment by Gadd28** [comment]
Is that means that only Australien people can use the application or some other countries can have it ?

**Comment by N0-0NE-Dev** [comment]
> Is that means that only Australien people can use the application or some other countries can have it ?

Australia and all countries in the middle east region. As, people in Egypt and Saudi Arabia also seem to have to problem with the app

**Comment by N0-0NE-Dev** [comment]
Probably other countries too, but those are the ones I am sure about.

**Comment by N0-0NE-Dev** [comment]
Hey @Sabonk @Heus-Sueh @Gadd28, as of version [1.1.3](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.3) you can choose hdw as a provider when you first launch the app and should work normally, please read the release notes for more information.
