### ISSUE TITLE
Create list of countries where NoFasel works

### ISSUE THREAD

**Issue by CodeCubeNeo** [N0-0NE-Dev/NoFasel#23]
Maybe add it to readme.md? It can be a checklist and you can ask people where the app works or have one issue pinned where people can say that their coutry doesnt block nofasel?

**Comment by N0-0NE-Dev** [comment]
Hopefully this will not be necessary, I am working on scraping a new website that will hopefully work in all countries.

**Comment by CodeCubeNeo** [comment]
AWESOME!

**Comment by N0-0NE-Dev** [comment]
Hey @CodeCubeNeo, as of version [1.1.3](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.3) you can choose hdw as a provider when you first launch the app and should work normally, please read the release notes for more information.
