### ISSUE TITLE
Ask for two permissions explanation

### ISSUE THREAD

**Issue by serrq** [N0-0NE-Dev/NoFasel#24]
In f-droid I found two permissions potentially dangerous for security reasons.

• This app can appear on top of other apps
• Play install referrer API

What are them? What do they do exactly?

Can be remove them?

**Comment by N0-0NE-Dev** [comment]
The app can appear on top of other apps as it supports picture-in-picture mode, so you can continue watching while doing something else on your device.

The referrer API is exposed by Google play to all apps automatically.

**Comment by N0-0NE-Dev** [comment]
I will not be removing them, but you are welcome to clone the repo remove whatever you want and build the app from source, build instructions can be found [here](https://github.com/N0-0NE-Dev/NoFasel/tree/main/android).
