### ISSUE TITLE
Loading 

### ISSUE THREAD

**Issue by johnadward2** [N0-0NE-Dev/NoFasel#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Version 

**Additional context**

**Comment by N0-0NE-Dev** [comment]
You have not filled any of the information in the template nor have you provided any screenshots, I don't know which part is "loading" or what exactly is happening and thus I cannot help you, please edit your issue and include more information.

**Comment by N0-0NE-Dev** [comment]
See #29

**Comment by johnadward2** [comment]
It's fixed thankyou 😊
