### ISSUE TITLE
Continuosly loading 

### ISSUE THREAD

**Issue by johnadward2** [N0-0NE-Dev/NoFasel#30]
![Screenshot_2023-02-27-19-38-04-52.png](https://user-images.githubusercontent.com/123066031/221594845-ac7be6e5-fc50-431a-9463-6cdf55ec8a7e.png)

**Comment by N0-0NE-Dev** [comment]
Use version [1.1.4](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.4), it should fix it. Also use hdw not fasel.

**Comment by ShareASmile** [comment]
Latest v1.1.4 released minutes ago also does not load hdw or fasel.

**Comment by N0-0NE-Dev** [comment]
@ShareASmile do a clean install

**Comment by ShareASmile** [comment]
Uninstalled & installed again same result.

**Comment by N0-0NE-Dev** [comment]
> Uninstalled & installed again same result.

Choose hdw not fasel, I tried and it is working just fine for me. Also, you have to wait for a bit for the files to be downloaded.

**Comment by ShareASmile** [comment]
I have chosen hdw waited for 3 minutes or so on LTE Connection only the spinner spins nothing loads.

**Comment by N0-0NE-Dev** [comment]
> I have chosen hdw waited for 3 minutes or so on LTE Connection only the spinner spins nothing loads.

Can you tell me the brand and model of phone you have?

**Comment by N0-0NE-Dev** [comment]
Also can you try version 1.0.6 and tell me if that loads.

**Comment by johnadward2** [comment]
Now hdw server working fine thankyou for your help❤️👍

**Comment by N0-0NE-Dev** [comment]
> Now hdw server working fine thankyou for your help❤️👍

Glad everything is working fine now! Also, thank you for bringing this issue to my attention and you have also indirectly brought new information to my attention that will help development in the future.
