### ISSUE TITLE
Using navigation gestures is hard

### ISSUE THREAD

**Issue by meenbeese** [N0-0NE-Dev/NoFasel#31]
**Is your feature request related to a problem? Please describe.**

When I try to go back from a menu, the app first opens the navigation bar, then lets me go back. Similarly, when I want to exit, I have to first swipe from the bottom to show the navigation bar, and then perform my wanted action.

**Describe the solution you'd like**

I think the app is opened in full-screen mode by default. I think that this is the wrong approach because it creates an additional step to perform any basic action such as going back and exiting. The bottom toolbar should not replace the navigation gesture, it should be above it.

**Describe alternatives you've considered**

None

**Additional context**

I added two screenshots for better comparison. The navigation gesture is shown by default in the first one, it has to be swiped to be shown in the second one.

![image](https://user-images.githubusercontent.com/114044633/222278583-82f83c44-35b0-48b0-bb38-8eb4681087cf.jpeg)

![image](https://user-images.githubusercontent.com/114044633/222278663-0a683045-9226-4c12-bb8e-7b4ae3e18b1a.jpeg)

**Comment by N0-0NE-Dev** [comment]
Hey @meenbeese, thanks for bringing this to my attention. As of commit 5ab36dc6d47e65ef23a60aa610a52b77b02a778f, I have made it so that the navigation bar is visible in all screens except for the watch screen, so you can have an uninterrupted view of the content. The changes will take effect as of version 1.1.6.

**Comment by meenbeese** [comment]
Hello @N0-0NE-Dev. Thank you for fixing the issue. Your app is really awesome. Regards.

**Comment by N0-0NE-Dev** [comment]
> Hello @N0-0NE-Dev. Thank you for fixing the issue. Your app is really awesome. Regards.

Thanks for the nice words, version 1.1.6 is now live!

**Comment by Hany-alhato** [comment]
Bro still not working ksa 🤕

**Comment by N0-0NE-Dev** [comment]
> Bro still not working ksa 🤕

What exactly is not working in KSA?

**Comment by Hany-alhato** [comment]
I replied to u in telegram
