### ISSUE TITLE
Explore section

### ISSUE THREAD

**Issue by Baker0o7** [N0-0NE-Dev/NoFasel#33]
Hi sir first will like to thank you for your hardworking and amazing app kindly would like to ask can you make the cards be 3 cards instead of 2 cards it will be nice, thanks again

**Comment by N0-0NE-Dev** [comment]
Hey @Baker0o7 I tested your idea and I really believe that 2 cards look better, but you are welcome to clone the repo and make the changes you want and compile the app, the building instructions are outdated as they state you need a premium fasel account, this is no longer the case you only need a free TMDb API key, I will be updating them later.
