### ISSUE TITLE
Download the whole season

### ISSUE THREAD

**Issue by not-programmer98** [N0-0NE-Dev/NoFasel#35]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a download button for the whole season

**Describe alternatives you've considered**
You may look at egybest-dl, it was doing this before the closure of the site

**Additional context**

**Comment by N0-0NE-Dev** [comment]
JavaScript is single threaded, meaning that the app can really only run one task at a time, so trying to extract links for all episodes of a season will take a long time. Making a python package for such thing makes much more sense, as multiprocessing in python is very easy.

**Comment by not-programmer98** [comment]
I don't mind waiting a long time to get a file of download links for 1dm, at least that's better than go to site a watch adds and repeat steps until get the whole season.
Maybe you make that run in background or just show a progress bar, Users could use any other program until the links are ready.
It's a good feature and there's no app provide now

**Comment by N0-0NE-Dev** [comment]
I will look more into it.

**Comment by not-programmer98** [comment]
Thank you

**Comment by N0-0NE-Dev** [comment]
Added in version [1.1.9](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.9), read the release notes for more details.
