### ISSUE TITLE
Episode number disappeared

### ISSUE THREAD

**Issue by not-programmer98** [N0-0NE-Dev/NoFasel#40]
**Describe the bug**
After the last update, I can't see episode numbers anymore

**To Reproduce**
I will provide a screenshot 

**Expected behavior**
I expect to see the episode numbers.
**Screenshots**
![IMG_20230306_201031](https://user-images.githubusercontent.com/126913926/223194894-16b19cd4-e08e-4605-becb-38a9696284dd.jpg)

**Smartphone (please complete the following information):**
 Not related to a specific one.

**Comment by N0-0NE-Dev** [comment]
After restarting the app does the bug still persist?

**Comment by not-programmer98** [comment]
Yes, I am using MIUI 13, android 12, last version on froid

**Comment by not-programmer98** [comment]
Update: I tried reinstalling the app and it worked fine.

**Comment by N0-0NE-Dev** [comment]
> Update: I tried reinstalling the app and it worked fine.

Ok great, I have no idea what the source of that bug would be.

**Comment by not-programmer98** [comment]
It happened again, I think this happen after opening the app then my lists tap then choose a series and the number of episodes disappears, it doesn't appear again unless removing the app data

**Comment by not-programmer98** [comment]
It's doesn't disappears but it turns black and it difficult to see it, I can see it if I increased brightness

**Comment by N0-0NE-Dev** [comment]
> It's doesn't disappears but it turns black and it difficult to see it, I can see it if I increased brightness

Yeah I can see that from the screenshot, there seem to be some bugs with the light theme, that's my fault I only really tested the dark theme when developing. I am currently working on migrating the code to bare react native and will work to fix the light theme issues in the process.

**Comment by N0-0NE-Dev** [comment]
Possibly fixed in [1.1.9](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.9), reopen if it persists.
