### ISSUE TITLE
Wont load. 

### ISSUE THREAD

**Issue by iAmMrGrim** [N0-0NE-Dev/NoFasel#41]
Hi. I am having trouble loading videos. Its in a boot loop. i have all permissions on. Is there something i am missing? 

Also i have a lot of hacks and mods.. so very possible two are fighting each other.

**Comment by N0-0NE-Dev** [comment]
Can you share a screenshot of what you are seeing? Are the action buttons not loading? Is the app not starting at all?

**Comment by iAmMrGrim** [comment]
This is screen shot

________________________________

**Comment by N0-0NE-Dev** [comment]
I am sorry, but I cannot see any screenshots attached, can you try and attach it again, preferably using the GitHub not email?

**Comment by iAmMrGrim** [comment]
https://github.com/iAmMrGrim/bug-reports-and-logs/find/main

**Comment by iAmMrGrim** [comment]
Bug report. Log. screen shot. :)

**Comment by N0-0NE-Dev** [comment]
Can you try a different move or tv show and tell me if that works?

**Comment by N0-0NE-Dev** [comment]
Also what provider are you using? HDwatched or FaselHD?

**Comment by iAmMrGrim** [comment]
Tried both
________________________________

**Comment by iAmMrGrim** [comment]
Tried 3 or 4 on each. Waited a few min and no luck. I then un installed and rebooted. Re install and clear cache. Same result
________________________________

**Comment by N0-0NE-Dev** [comment]
Can you try with a vpn? I recommend you use proton vpn.

**Comment by iAmMrGrim** [comment]
Ok will do
________________________________

**Comment by gad0ra** [comment]
Same problem. Tried proton and OpenVpn..
Arabic series load fine tho

**Comment by N0-0NE-Dev** [comment]
@iAmMrGrim @iAmMrGrim, can you make sure that [this](https://play.google.com/store/apps/details?id=com.google.android.webview) app is installed and updated to the latest version?

**Comment by N0-0NE-Dev** [comment]
Have you checked for the app I mentioned above?

**Comment by gad0ra** [comment]
It worked.
Thanks mate

**Comment by N0-0NE-Dev** [comment]
Stale
