### ISSUE TITLE
Please add other Languages Support

### ISSUE THREAD

**Issue by apisword** [N0-0NE-Dev/NoFasel#42]
I want to watch them in German. And other ppl may want to watch in other languages too.

**Comment by N0-0NE-Dev** [comment]
Please look through closed issues before opening a new one. If you select HDwatched as a provider you get content with no subtitles which you can then download subtitles for (from [here](https://subscene.com/) for example) and add the subtitles to the content using a video player like [vlc](https://play.google.com/store/apps/details?id=org.videolan.vlc). For more information read #21 and the release notes for version [1.1.3](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.3).
