### ISSUE TITLE
Some series Not Found in download season page 

### ISSUE THREAD

**Issue by not-programmer98** [N0-0NE-Dev/NoFasel#44]
For example "Your honor" I can find it in explore page
![Imagepipe_0](https://user-images.githubusercontent.com/126913926/226205596-fb75b8cd-c1ed-4d93-85f2-2f9bd39fcbc5.jpg)
But in download season page it doesn't exist
![Imagepipe_0](https://user-images.githubusercontent.com/126913926/226205630-35e5f702-9ace-4667-b504-1e9c39f3c63b.jpg)

**Comment by N0-0NE-Dev** [comment]
Yeah that's because it's not on wecima, there is nothing I can really do about that.

**Comment by not-programmer98** [comment]
It's on wecima 
![Imagepipe_0](https://user-images.githubusercontent.com/126913926/226222031-1c7b124f-1102-4c59-b0be-ccca7432d58b.jpg)

**Comment by N0-0NE-Dev** [comment]
Share the link please.

**Comment by N0-0NE-Dev** [comment]
Yeah I can see it now, but I do not think they have a link to download the entire season, if you find one, send it and I add it.

**Comment by not-programmer98** [comment]
No there is not. Probably all new series doesn't have that option on their site.
