### ISSUE TITLE
Tmdb

### ISSUE THREAD

**Issue by Baker0o7** [N0-0NE-Dev/NoFasel#47]
When I click on tmdb icon the app close itself

**Comment by N0-0NE-Dev** [comment]
Thanks for bringing this to my attention, I will work on fixing it in the next versions.

**Comment by not-programmer98** [comment]
I can assure this

**Comment by N0-0NE-Dev** [comment]
Fixed in [1.2.2](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.2.2).
