### ISSUE TITLE
Add an option for different subtitle languages

### ISSUE THREAD

**Issue by CodeCubeNeo** [N0-0NE-Dev/NoFasel#5]
I think it is very important to add an option, which subtitles to download in the select menu or from the video player. Maybe you can download the subs from opensubtitles or smth?

**Comment by N0-0NE-Dev** [comment]
Hi @CodeCubeNeo, I have been thinking about that and trying to do it. I found a good website to scrape the content from, as the website I currently use have the subtitles baked into the video. I will probably leave the downloading part up to the users and just prompt them to select it. Thanks for your suggestion!

**Comment by N0-0NE-Dev** [comment]
Hey as of version [1.1.3](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.3) you can choose hdw as a provider when you first launch the app. All the content from hdw had no subtitles by default you can use an external video player like [vlc ](https://play.google.com/store/apps/details?id=org.videolan.vlc) to add subtitles.
