### ISSUE TITLE
Some shows stuck on loading?

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [N0-0NE-Dev/NoFasel#50]
When watching shows, most work fine! breaking bad; better call saul; etc.
And movies also work! El camino; The truman show; etc.
BUUUT... for some reason animated shows/cartoons get stuck at loading
i tried to watch gravity falls and adventure time, and they both where stuck at loading...
so tested watching the simpsons and again... loading forever.
family guy worked! which was weird, but most cartoons didnt!

Maybe its a problem with my phone idk:
 - Device: Samsung a33 5g
 - OS: Android/OneUi
 - Version: android 13

**Comment by N0-0NE-Dev** [comment]
Hey @TeaEndsAcronyms, some entries on the app were scraped from HDW which has since stopped working and were removed from the app, however the content was not removed from the content files. I have gone through and removed these entries and now everything you see in search should hopefully work.
