### ISSUE TITLE
[Bug] App Crashes When Using Search Filter, v1.2.3

### ISSUE THREAD

**Issue by DarkCrypt** [N0-0NE-Dev/NoFasel#51]
**Describe the bug**
App crashes when selecting any category or genre in search filter.

**To Reproduce**
1. Go to explore page
2. Click on filter next to search bar
3. Click any category or genre
4. App crashes everytime.

**Expected behavior**
App doesn't crash and instead navigates to the selected category or genre.

**Screenshots**
Self explanatory.

**Smartphone (please complete the following information):**
 - Device: OnePlus 9 Pro
 - OS: OxygenOS 13
 - Version: Android 13

**Additional context**
App version: v1.2.3.

**Comment by N0-0NE-Dev** [comment]
Thanks for bringing this to my attention, I will fix it in the next release.

**Comment by N0-0NE-Dev** [comment]
Turns out it was a problem with the content files, I have fixed them now, try to force update content from the settings.

**Comment by DarkCrypt** [comment]
Filters working and no crashes. 👍
