### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Ha62009** [N0-0NE-Dev/NoFasel#52]
I have a problem. When I pressed play nothing happened.
![Screenshot_2023-05-23-20-09-31-86_04aad770f80d7e5bbd6c1fff15b6a3f5](https://github.com/N0-0NE-Dev/NoFasel/assets/134430123/9c90baee-7d65-448c-968f-86965d1b5d9c)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: oneplus 7 pro
 - OS: Android 
 - Version 12

**Additional context**

**Comment by N0-0NE-Dev** [comment]
Fixed in version [1.2.4](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.2.4).
