### ISSUE TITLE
Prepare for taked0*n re$uest

### ISSUE THREAD

**Issue by Leichesters** [N0-0NE-Dev/NoFasel#55]
Hey @N0-0NE-Dev, first of all: Thank you for creating NoFasel! If I read your profile correctly, we both live in relatively poor circumstances (no offense), so NoFasel really helps me access movies and series really easily. It's really good that we live in a time where knowing stuff can beat being born rich and having an extremely privileged life.

Anyway, I guess that sooner or later NoFasel will face a taked0wn re$uest. To prepare for that situation, I'd strongly recommend you doing the following:

* Set up a pgp key - This allows the community verify your authenticity (basically it proves that you are really who you are)
* Mirror your source code to another platform - I'd recommend mirroring your code to multiple hosters + doing some backups. [Codeberg](https://codeberg.org/) is very strong in favor of privacy, but they are German servers. You could also self-host your own GitLab on Iceland for example (if you need help with this feel free to reach out to me). Another option would also to host it on the darknet. This would be the most secure method, but kinda hard to advertise from.

I hope you don't take this as an offense, I just want to help NoFasel stay up, as you have put a lot of effort into it :smile:

**Comment by N0-0NE-Dev** [comment]
Hey thanks for both the nice words and the advice! I will be taking a deeper look at them and seeing what works! A lot of NoFasel is going to be changing soon anyway with the implementation of the consumet API, so while working on that I will definitely take your advice into account!
