### ISSUE TITLE
App Orientation

### ISSUE THREAD

**Issue by ZooNooU** [N0-0NE-Dev/NoFasel#7]
hello dev!
thanks for this amazing app,
can you make the app follow's system orientation instead of sensor's one?
because it's annoying when I lay on my side to watch vertically but the app's uses sensor to determine orientation so it goes horizontally, which is not what I want.

**Comment by N0-0NE-Dev** [comment]
Hi @ZooNooU, I fixed this issue in 28e8d80779ca2f4475f69060b529dd8f5af41f6f and pushed an OTA update. Restart the app a couple of times and it all the screens will now respect the auto rotate lock, expect for the watch screen, which will continue to rotate freely. Thanks for your suggestion!
