### ISSUE TITLE
Season and episode

### ISSUE THREAD

**Issue by Baker0o7** [N0-0NE-Dev/NoFasel#8]
Hi sir I would like to thank you first for your hardworking and amazing app second it will be nice if you will be able to add dimming the season or the episode which have been watched  thanks again

**Comment by N0-0NE-Dev** [comment]
Hey @Baker0o7, as of version [1.1.1](https://github.com/N0-0NE-Dev/NoFasel/releases/tag/v1.1.1), there is a small progress bar that appears below each episode indicating how much of the episode you have watched.
